packageExtensions:
  "@remix-run/node@*":
    dependencies:
      react: "*"
      react-dom: "*"
  remix-app-template@*:
    dependencies:
      esbuild-register: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
